services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    image: workshop-docs-mkdocs:latest
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    ports:
      - "8080:80"
    environment:
      PYTHONUNBUFFERED: 1
      VIRTUAL_HOST: "docs.langfuse-workshop.ru"
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: "docs.langfuse-workshop.ru"
      LETSENCRYPT_EMAIL: "bocharovf@gmail.com"
    networks:
     - main

networks:
  main:
    external:
      name: primary-network